#!/usr/bin/env python3
"""Regenerate question-bank/used-ledger.md from every past-paper reference in the repo.

Run this BEFORE building any mock. A question that appears in the ledger is not unseen.
"""
import re, os, collections

PAT = re.compile(
    r'\b(1[6-9]|2[0-5])(?:st|nd|rd|th)?\s*(?:sitting\s*)?(?:Set\s*[AB]\s*)?([LN]-?\d)\s*(\([A-D]\))?',
    re.I)

def main():
    hits = collections.defaultdict(set)
    for d in ('curriculum', 'assessments'):
        for f in sorted(os.listdir(d)):
            if not f.endswith('.md'):
                continue
            for m in PAT.finditer(open(os.path.join(d, f)).read()):
                key = (int(m.group(1)), m.group(2).upper().replace('-', ''),
                       (m.group(3) or '').upper())
                hits[key].add(f[:-3])

    out = ["# Used-Question Ledger", "",
           "**Auto-generated by `tools/ledger.py`. Every past-paper question referenced",
           "anywhere in `curriculum/` or `assessments/`, with the files referencing it.**", "",
           "> **Why this exists.** Mock 1 was issued with the line *\"Every question here is",
           "> unseen\"*. Four of its eight questions had already been assigned — Day 1's Block",
           "> B3, Day 13's Block C, Day 13 Drill 68 and the sector diagnostic's Q2. Two of",
           "> those had been written days earlier by the same hand that called them unseen.",
           "> The claim was made from memory instead of from a check.",
           ">",
           "> **Rule: no question enters a mock until it has been looked up here.**",
           "> Regenerate with `python3 tools/ledger.py` before building any paper.", "",
           "| Sitting | Q | Referenced in |", "|---|---|---|"]
    for (sit, q, opt) in sorted(hits):
        files = sorted(hits[(sit, q, opt)])
        out.append("| %dth | %s%s | %s |" % (sit, q, opt, ", ".join("`%s`" % x for x in files)))
    out += ["", "**%d distinct questions used so far.**" % len(hits)]
    open('question-bank/used-ledger.md', 'w').write("\n".join(out) + "\n")
    print("%d questions written to question-bank/used-ledger.md" % len(hits))

if __name__ == '__main__':
    main()
