#!/usr/bin/env python3
"""Regenerate question-bank/used-ledger.md from every past-paper reference in the repo.

Run this BEFORE building any mock. A question that appears in the ledger is not unseen.

Two reference forms are recognised, because the curriculum uses both:
  A.  "21st N-1", "24th sitting N-4(C)", "18th Set A L-1"
  B.  "`papers/21-1.pdf`, question N-1"   <- the form the mocks use
Form B was missed until 20 Sep, which left the ledger blind to both mock papers.
"""
import re, os, collections

# Form A: sitting number written out, question label follows
FORM_A = re.compile(
    r'\b(1[6-9]|2[0-5])(?:st|nd|rd|th)\s*(?:sitting\s*)?(?:Set\s*[AB]\s*)?([LN]-?\d)\s*(\([A-D]\))?',
    re.I)
# Form B: papers/<sitting>-<set>.pdf ... question label within the next 40 characters
FORM_B = re.compile(
    r'papers/(1[6-9]|2[0-5])(?:-[12])?\.pdf.{0,40}?\b([LN]-?\d)\s*(\([A-D]\))?',
    re.I | re.S)

def main():
    hits = collections.defaultdict(set)
    for d in ('curriculum', 'assessments'):
        for f in sorted(os.listdir(d)):
            if not f.endswith('.md'):
                continue
            text = open(os.path.join(d, f)).read()
            for pat in (FORM_A, FORM_B):
                for m in pat.finditer(text):
                    key = (int(m.group(1)), m.group(2).upper().replace('-', ''),
                           (m.group(3) or '').upper())
                    hits[key].add(f[:-3])

    out = ["# Used-Question Ledger", "",
           "**Auto-generated by `tools/ledger.py`. Every past-paper question referenced",
           "anywhere in `curriculum/` or `assessments/`, with the files referencing it.**", "",
           "> **Why this exists.** Mock 1 was issued with the line *\"Every question here is",
           "> unseen\"*. Four of its eight questions had already been assigned. The claim was",
           "> made from memory instead of from a check.",
           ">",
           "> **And the first version of this script was itself incomplete** — it matched",
           "> only \"21st N-1\" and missed \"`papers/21-1.pdf`, question N-1\", which is the",
           "> form both mocks use. Fixed 20 Sep. A guard that does not cover the files it",
           "> exists to guard is worse than none, because it is trusted.",
           ">",
           "> **Rule: no question enters a paper until it has been looked up here, AND",
           "> given a data-item prerequisite check.** Those are two different checks —",
           "> see `assessments/framework.md`.", "",
           "| Sitting | Q | Referenced in |", "|---|---|---|"]
    for (sit, q, opt) in sorted(hits):
        files = sorted(hits[(sit, q, opt)])
        out.append("| %dth | %s%s | %s |" % (sit, q, opt, ", ".join("`%s`" % x for x in files)))
    out += ["", "**%d distinct questions used so far.**" % len(hits)]
    open('question-bank/used-ledger.md', 'w').write("\n".join(out) + "\n")
    print("%d questions written" % len(hits))

if __name__ == '__main__':
    main()
